POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "event 2",
    "details": null,
    "maximumAttendees": 1
}


###


POST http://localhost:3333/events/44a3b8f2-c939-442e-8608-0d1bb62d49cf/attendees
Content-Type: application/json

{
    "name": "Paulo Parizz",
    "email": "paulo2122@gmail.com.br"
}


###


GET http://localhost:3333/events/44a3b8f2-c939-442e-8608-0d1bb62d49cf


###


GET http://localhost:3333/attendees/2/badge


###


GET http://localhost:3333/attendees/8/check-in


###

GET http://localhost:3333/events/44a3b8f2-c939-442e-8608-0d1bb62d49cf/attendees?query=Joao

