POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "tnlw",
    "details": null,
    "maximumAttendees": 1
}


###


POST http://localhost:3333/events/203ddf17-c9fe-41ba-874a-b121a2ae64dd/attendees
Content-Type: application/json

{
    "name": "Paulo Parizz",
    "email": "paulo21@gmail.com.br"
}